### ISSUE TITLE
Angular File Manager Integration - PHP (Symfony4) BackEnd File Provider

### ISSUE THREAD

**Issue by YassineBenJlila** [SyncfusionExamples/ej2-angular-7-file-manager#3]
Hi Syncfusion Support,
i want to match your "SyncfusionExamples/ej2-angular-7-file-manager" with my PHP-Symfony API.
please there is a documentation support for that issue ?!

**Comment by PiramanayagamR** [comment]
Hi @YassineBenJlila ,

Greetings from Syncfusion support.

We have already validated this requirement and considered this as a feature from our end, it will be included in our anyone of upcoming volume release.

Generally, we will plan the component implementation based on customer request count and wish-list plan.

You can track the component status through your portal link.
https://www.syncfusion.com/feedback/12439/angular-file-manager-integration-with-php-symfony4-back-end-file-provider

Regards,
Piramanayagam R

**Comment by YassineBenJlila** [comment]
thank you @PiramanayagamR :).
